{% set name = "wandb" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9b4bf790c468e7b350eeaba2de002672a5cbaa3049899ab060940e2388f429a

build:
  number: 0
  skip: true  # [py<38]
  # skipping s390x as we do not have setproctitle package for this arch. Also, the current package 
  # will go to Snowflake-specific channel only, so there is no urgency to build it on s390x.
  skip: true  # [linux and s390x]
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv

requirements:
  host:
    - pip
    - python
    - hatchling
    - typing_extensions
    - pytest
    - go
    - {{ compiler('rust') }}

  run:
    - click >=7.1,!=8.0.0
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - protobuf >=3.12.0,!=4.21.0,!=5.28.0,<6
    - psutil >=5.0.0
    - python
    - sentry-sdk >=2.0.0
    - setuptools
    - pyyaml
    - requests >=2.0.0,<3
    - setproctitle
    - typing-extensions <5,>=4.4  # [py<312]
    - platformdirs
    - pydantic >=2.6,<3
    - eval-type-backport  # [py<310]

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
  requires:
    - pip

about:
  home: https://wandb.ai/site
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A CLI and library for interacting with the Weights and Biases API.
  description:  |
    WandB (short for \"Weights and Biases\") is a Python library that provides a set of tools 
    for visualizing and tracking machine learning experiments. It is designed to make it easy 
    to track the performance of machine learning models and experiments over time, and to 
    collaborate with others on machine learning projects.
  doc_url: https://docs.wandb.ai/
  dev_url: https://github.com/wandb/wandb

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - synapticarbors
