{% set name = "wandb" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: f860af2bcb29c83e41729557aa9519e3cc5264c9bccc05e32d6f77b91c264ba1

build:
  number: 0
  skip: true  # [py<38]
  # we don't have 'go-cgo' compiler for s390x
  skip: true  # [linux and s390x]
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('go-cgo') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}

  host:
    - pip
    - python
    - hatchling
    - setuptools
    - typing-extensions

  run:
    - click >=7.1,!=8.0.0
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - protobuf >=3.19.0,!=4.21.0,!=5.28.0,<6
    - psutil >=5.0.0
    - python
    - sentry-sdk >=2.0.0
    - pyyaml
    - requests >=2.0.0,<3
    - setproctitle
    - typing-extensions >=4.4,<5  # [py<312]
    - platformdirs
    - pydantic >=2.6,<3
    - eval-type-backport  # [py<310]

test:
  source_files:
    - tests
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help

    # here we remove all the tests which are out of scope of build, mostly because they're integrational
    # and/or require packages we don't have or running docker etc etc
    - rm -rf tests/system_tests  # because of kubernetes_asyncio, stable_baseline3, google-cloud-compute and other deps
    - rm -rf tests/unit_tests/test_launch  # because of Azure and gcp
    - rm tests/unit_tests/test_data_types.py  # because of moviepy
    - rm tests/unit_tests/test_internal_api.py  # because of TestAzure
    - rm tests/unit_tests/test_analytics/test_sentry.py
    - rm tests/unit_tests/test_lib/test_credentials.py
    - rm tests/unit_tests/test_media/test_media_logging.py
    - rm tests/unit_tests/test_system_metrics/test_open_metrics.py
    - rm tests/unit_tests/test_artifacts/test_storage.py
    - rm tests/unit_tests/test_lib/test_hashutil.py
    - rm tests/unit_tests/test_cli.py  # using docker
    - rm tests/unit_tests/test_lib/test_git.py
    - export GIT_PYTHON_REFRESH=quiet  # [not win]
    - pytest tests -v

  requires:
    - python
    - pip
    - pytest
    - pyte
    - hypothesis
    - torcheval
    - parameterized
    - matplotlib
    - tenacity
    - tqdm
    - plotly
    - pytest-mock
    - pandas
    - scikit-learn

about:
  home: https://wandb.ai/site
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A CLI and library for interacting with the Weights and Biases API.
  description:  |
    WandB (short for \"Weights and Biases\") is a Python library that provides a set of tools 
    for visualizing and tracking machine learning experiments. It is designed to make it easy 
    to track the performance of machine learning models and experiments over time, and to 
    collaborate with others on machine learning projects.
  doc_url: https://docs.wandb.ai/
  dev_url: https://github.com/wandb/wandb

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - synapticarbors
