{% set name = "wandb" %}
{% set version = "0.13.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wandb-{{ version }}.tar.gz
  sha256: f2b065d1c732e8e1828fabe720dc82f12e6109d0d2bbfbcccc17eaefae0fd7c9

build:
  number: 0
  skip: true  # [py<38]
  # skipping s390x as we do not have setproctitle package for this arch. Also, the current package 
  # will go to Snowflake-specific channel only, so there is no urgency to build it on s390x.
  skip: true  # [linux and s390x]
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - wheel
    - python 
    - setuptools <64
  run:
    - click >=7.0,!=8.0.0
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - pathtools
    - protobuf >=3.20.3,!=4.21.0,<5
    - psutil >=5.0.0
    - python 
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=1.0.0
    - setproctitle
    - appdirs >=1.4.3
    - typing_extensions  # [py<310]

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
  requires:
    - pip

about:
  home: https://wandb.ai/site
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A CLI and library for interacting with the Weights and Biases API.
  description:  |
    WandB (short for \"Weights and Biases\") is a Python library that provides a set of tools 
    for visualizing and tracking machine learning experiments. It is designed to make it easy 
    to track the performance of machine learning models and experiments over time, and to 
    collaborate with others on machine learning projects.
  doc_url: https://docs.wandb.ai/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - synapticarbors
